---
DataSetConfig:
  phenotype_id: null
  classification: null
  file_format: "plink"
  populations: ["white_british"]
  include_x_chromosome: false
  maf_threshold: 0.05
  covar_config:
    include_covars: true
    covar_keys: ["age", "sex", "Global_PC1", "Global_PC2", "Global_PC3", "Global_PC4", "Global_PC5", "Global_PC6", "Global_PC7", "Global_PC8", "Global_PC9", "Global_PC10"]
  sample_sampling:
    strat: "random"
    max_samples: 120_000
    k: 5
    balance_pops: false
  variant_sampling:
    strat: "random"
    max_features: 100_000
    ld_config:
      prune_kb: 250
      prune_step: 50
      prune_r2: 0.1
      tau: 0.1
      ld_window_kb: 1_000
      ld_window: 50_000
      eps: 0.0
      eps_schedule: "constant"
      eps_step_size: 0.0
    gwas_config:
      path: "..."
      snps_column: "ID"
      pvalue_column: "p_value"
      sep: '\s+'
      nlogpvalue_column: "LOG10P"
      impute_val: 0.1
    window_overlap_ratio: 0.0
---
GenomenModelConfig:
  covar_config:
    covar_strat: null
    model_config:
      model_name: linear
      hyperparameters: {}
      balance_classes: false
  geno_config:
    n_estimators: 32
    compute_interactions: True
    preprocessing_config:
      z_score_thresh: 0.0
      standard_labels: false
      feature_selection:
        method: "k_best"  # Options: "none", "k_best", "percentile", "variance_threshold", "mutual_info", "rfe"
        k: 20_000
        percentile: 0.75
        variance_threshold: 0.05
        score_func: null
    model_config:
      model_name: ensemble
      ensemble_estimator_names: ["linear_l1", "lightgbm"]
      hyperparameters: 
        linear_l1:
          alpha: 0.01
        lightgbm:
          bagging_fraction: 0.6232546393535136
          bagging_freq: 1
          feature_fraction: 0.7568699255535379
          learning_rate: 0.020426221815062907
          max_bin: 289
          max_depth: 14
          min_child_samples: 13
          min_child_weight: 5.174997310706651
          min_data_in_leaf: 286
          min_gain_to_split: 1.7960224741869382
          n_estimators: 1500
          num_leaves: 180
          path_smooth: 40.095909854952
      balance_classes: true     
    aggregator_config:
      filter_strat: "positive"
      agg_strat: "stacking"
      use_summary_stats: false
      model_config: 
        model_name: linear_l2
        hyperparameters: 
          alpha: 0.01
        balance_classes: true
      p: 0.7
      temp: 0.05
---
TrainConfig:
  batch_size: 2
  n_jobs: 28
  backend: "cpu"
  ram_mb: 100_000
  scorer: null
  patience: 10
  seed: 42
  log_with_wandb: true
  save_annotation: false
  save_model: false
